# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Node.js Package to NPM

on:
    release:
        types: [created]

jobs:
    # Pulishes this package to npm
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '18.x'
                  registry-url: https://registry.npmjs.org/
            # Installing dependencies
            - run: npm install

            # Building the package
            - run: npm run build

            # Publishing
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.npm_token}}
